[character]
success_symbol = "[ğŸš€](bold green)"

[cmd_duration]
min_time = 500
format = "â±  [$duration](bold yellow)"

[hostname]
ssh_only = true
format =  "ğŸ“¡  [$hostname](bold red) "
trim_at = ""
disabled = false

